* Woozie


[[https://oozie.apache.org/][Oozie]] functionality in the emacs environment!

Woozie is an Emacs library with functions that increase Oozie-related productivity.
This includes, but is not limited to:
+ functions that simplify building workflow definitions;
+ functions that simplify building workflow configuration files;
+ functions for validating workflow definitions;
+ functions for extracting variable lists from different types of Hadoop/Ooozie files;
+ functions for visualizing workflows.

** User Documentation

Including installation instructions and examples, can be found [[./docs/index.org][here]].


** Running Unit Tests

To run unit tests for this code: =make=

** Installation

Installation is straightforward. Just copy the file =woozie.el= to your machine and add the following to your emacs configuration:

#+BEGIN_SRC emacs-lisp
(load-file "path/to/woozie.el")
#+END_SRC

All functions start with `woozie-`, so feel free to use `ctrl-h f woozie-<TAB>` to explore
the available functionality.







