* Woozie


[[https://oozie.apache.org/][Oozie]] functionality in the emacs environment!

Woozie is an Emacs major mode with functions that increase Oozie-related productivity.
This includes, but is not limited to:
+ functions that simplify building workflow definitions;
+ functions that simplify building workflow configuration files;
+ functions for validating workflow definitions;
+ functions for extracting variable lists from different types of Hadoop/Ooozie files;
+ functions for visualizing workflows.

** User Documentation

+ Instructions on installation and usage can be found [[./docs/index.org][here]].
+ A tutorial on creating workflows with Emacs and Woozie can be found [[./docs/tutorial.org][here]].

** Running Unit Tests

To run unit tests for this code: =make=

** Installation

Installation is straightforward. Download =woozie.el= to your computer and, inside Emacs,
run =package-install-file=, passing the path to the downloaded file as a parameter.
Enable =woozie-mode= when you are ready to edit your workflow definition file and you are good
to go.








